### ISSUE TITLE
`ruby-ci.yml`: expose setup-ruby inputs

### ISSUE THREAD

**Issue by dentarg** [84codes/actions#6]
I think it would be good if you could control certain inputs to setup-ruby when using `ruby-ci.yml`

All inputs are listed in https://github.com/ruby/setup-ruby/blob/master/action.yml

The ones I've felt the need for

* `bundler-cache`
* `cache-version`

but these also make sense I think

* `ruby-version` version to use (we default this to .ruby-version now)
* `rubygems` version to use
* `bundler` version to use
* `working-directory` – would have to be set for all steps in `ruby-ci.yml` to be useful I think

Don't think we are interested in `self-hosted` and `windows-toolchain`

WDYT @jage @walro?

**Comment by dentarg** [comment]
> The ones I've felt the need for
> 
> * `bundler-cache`
> * `cache-version`

`bundler-cache` if we have some gem where we want to turn it off
`cache-version` to just be able to solve cache problems if they pop up

**Comment by walro** [comment]
Sounds good to me, in the "also list", I think we should at least do `ruby-version` and then add the others when/if needed.

**Comment by jage** [comment]
Sounds reasonable.

**Comment by dentarg** [comment]
> Sounds good to me, in the "also list", I think we should at least do `ruby-version` and then add the others when/if needed.

My bad to include it, we already support it :) 

https://github.com/84codes/actions/blob/5902dc203d87c953f47121b908d30282d09d72bb/.github/workflows/ruby-ci.yml#L5-L10

**Comment by dentarg** [comment]
> we already support it

...in `tests` job, but not `lint` job, but fixing it at https://github.com/84codes/actions/pull/7/commits/1ac0d721d3fd9355fe4620d2984b158af0bb03db
